name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.5
        with:
          node-version: 14.x
      
      # Instalar as dependências do projeto
      - name: Install dependecies
        run: yarn
        
      # Executar a build do projeto
      - name: Run build
        run: yarn build
        
      # Copiar código novo para dentro do servidor/vps  
      - name: Copy files to server/vps
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: ".,!node_modules"
          target: "~/app/gobarber-nodejs"
      
      # Executar 'yarn' no servidor/vps
            
      # Executar as migrations do typeORM
      
      # Reiniciar servidor node.js
